name: CI-CD-Frontend

on:
  push:
    branches: [ main,dev ]
  pull_request:
    branches: [ main,dev ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Set env variable
      run: echo "ARTIFACT_NAME=${{ env.NODE_APP }}-dist-${{ github.sha }}.tar.gz" >> $GITHUB_ENV

    - name: npm install, build, and test
      run: |
        npm install
        npm run build
        npm run test --if-present

    - name: Create deployment artifacts
      env:
        GITHUB_SHA: ${{ github.sha }}
      #run: tar -czf "${GITHUB_SHA}"-dist.tar.gz ./dist/
      run: tar -czf ${{ env.ARTIFACT_NAME }} ./dist/


    - name: Store artifact for distribution
      uses: actions/upload-artifact@v3
      with:
        name: app-build
        path: ${{ env.ARTIFACT_NAME }}
    
  DeployDev:
    name: Deploy to Dev 
#   if: github.event_name == 'pull_request'
    if: github.event.ref == 'refs/heads/dev'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: dev
      #url: 'http://www.myapp.com'
      host: ${{ secrets.DEV_SSH_HOST }}
      username: ${{ secrets.DEV_SSH_USER }}
      key: ${{ secrets.DEV_SSH_KEY }}
      port: ${{ secrets.DEV_SSH_PORT }}
      path: ${{ secrets.DEV_SERVER_PATH }}
      #url: 'http://dev.myapp.com'
    steps:
    - name: Set env variable
      run: echo "ARTIFACT_NAME=${{ env.NODE_APP }}-dist-${{ github.sha }}.tar.gz" >> $GITHUB_ENV

    - uses: actions/download-artifact@v3
      with:
        name: app-build

    - name: Upload Artifact
      uses: appleboy/scp-action@master
      with:
        host: ${{ env.host }}
        username: ${{ env.username }}
        key: ${{ env.key }}
        port: ${{ env.port}}
        source: ${{ env.ARTIFACT_NAME }}
        target: ${{ env.path }}

    - name: Extract Artifact
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ env.host }}
        username: ${{ env.username }}
        key: ${{ env.key }}
        port: ${{ env.port}}
        script: |
          cd ${{ env.path }}
          mkdir -p templates
          cd templates
          rm -irf !'(*.tar.gz)'           
          mv ../${{ env.ARTIFACT_NAME }} .
          echo ".....Before extracting Dev artifact....."
          tar -xzvf ${{ env.ARTIFACT_NAME }} --strip-components 2
          rm *.tar.gz
          echo ".....Before restarting Dev Apache....."
          sudo systemctl restart apache2
          echo ".....Deployed and Restarted Dev Apache....."
              
  DeployProd:
    name: Deploy to Production 
#    needs: [DeployDev]
    if: github.event.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: 
      name: production
      #url: 'http://www.myapp.com'
      host: ${{ secrets.PROD_SSH_HOST }}
      username: ${{ secrets.PROD_SSH_USER }}
      key: ${{ secrets.PROD_SSH_KEY }}
      port: ${{ secrets.PROD_SSH_PORT }}
      path: ${{ secrets.PROD_SERVER_PATH }}
    steps:
    - name: Set env variable
      run: echo "ARTIFACT_NAME=${{ env.NODE_APP }}-dist-${{ github.sha }}.tar.gz" >> $GITHUB_ENV

    - uses: actions/download-artifact@v3
      with:
        name: app-build

    - name: Upload Artifact
      uses: appleboy/scp-action@master
      with:
        host: ${{ env.host }}
        username: ${{ env.username }}
        key: ${{ env.key }}
        port: ${{ env.port}}
        source: ${{ env.ARTIFACT_NAME }}
        target: ${{ env.path }}

    - name: Extract Artifact
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ env.host }}
        username: ${{ env.username }}
        key: ${{ env.key }}
        port: ${{ env.port}}
        script: |
          cd ${{ env.path }}
          mkdir -p templates
          cd templates
          rm -irf !'(*.tar.gz)'           
          mv ../${{ env.ARTIFACT_NAME }} .
          echo ".....Before extracting artifact....."
          tar -xzvf ${{ env.ARTIFACT_NAME }} --strip-components 2
          rm *.tar.gz
          echo ".....Before restarting Apache server....."
          sudo systemctl restart apache2
          echo ".....Deployed and Restarted Apache....."


  # DeployStaging:
  #   name: Deploy to Staging 
  #   if: github.event.ref == 'refs/heads/main'
  #   needs: [Build]
  #   runs-on: ubuntu-latest
  #   environment: 
  #     name: Staging
  #     # url: 'http://test.myapp.com'
  #   steps:
  #     - name: Deploy
  #       run: echo I am deploying! 
    